export const GET_COCKTAILS='GET_COCKTAILS';
export const GET_COCKTAIL='GET_COCKTAIL'
export const LOAD_COCKTAILS='LOAD_COCKTAILS';
export const COCKTAILS_ERRORS='COCKTAILS_ERRORS';
export const GET_COCKTAILS_LOAD='GET_COCKTAILS_LOAD'